name: deployProxy

on: 
  workflow_dispatch:
    inputs:      
        network:
          description: 'Enter the network to deploy to: EWC or Volta'
          options:
          - volta
          - ewc
          required: true
          default: volta
    
env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  MY_GH_TOKEN: ${{ secrets.MY_GH_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node:version: current
          
      - name: Install depndencies 
        run: npm ci
        
      - name: Installing hardhat
        run: npm install -g hardhat
        
      - name: Compile contract
        run: npx hardhat compile

      - name: Test contract
        run: npx hardhat test

      - name: Deploy contract
        run: |
          PROXY_ADDRESS=$(npx hardhat run scripts/deployProxy.js --network ${{ inputs.network }} | grep 'proxy address: ' | cut -d ' ' -f 3)

        
      - name: Create or update secret
        run: |
          curl -X PUT \
          -H "Authorization: Bearer ${{ secrets.MY_GH_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/ihamzazam/te/actions/secrets/proxy_add" \
          -d "{\"encrypted_value\":\"$(echo -n "$PROXY_ADDRESS" | base64)\"}"
