name: deployProxy

on: 
  workflow_dispatch:
    inputs:      
        network:
          description: 'Enter the network to deploy to: EWC or Volta'
          options:
          - volta
          - ewc
          required: true
          default: volta
    
env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node:version: current
          
      - name: Install depndencies 
        run: npm ci
        
      - name: Installing hardhat
        run: npm install -g hardhat
        
      - name: Compile contract
        run: npx hardhat compile

      - name: Test contract
        run: npx hardhat test

      - name: Deploy contract
        run: |
          npx hardhat run scripts/deployProxy.js --network ${{ inputs.network }}

          new_proxyAddress=$(echo $PIPELINE_OUTPUT | grep -oEi "0x[[:xdigit:]]+")
          
          sed -i "s/const proxyAddress = \".*\";/const proxyAddress = \"$new_proxyAddress\";/g" upgrade.js
          
          git add upgrade.js
          git commit -m "Update proxy address"
          git push 

