name: deployProxy

on: 
  workflow_dispatch:
    inputs:      
        network:
          description: 'Enter the network to deploy to: EWC or Volta'
          options:
          - volta
          - ewc
          required: true
          default: volta
    
env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  MY_GH_TOKEN: ${{ secrets.MY_GH_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node:version: current
          
      - name: Install depndencies 
        run: npm ci
        
      - name: Installing hardhat
        run: npm install -g hardhat
        
      - name: Compile contract
        run: npx hardhat compile

      - name: Test contract
        run: npx hardhat test

      - name: Deploy contract
        run: |
          PROXY_ADDRESS=$(npx hardhat run scripts/deployProxy.js --network $NETWORK | grep 'proxy address: ' | cut -d ' ' -f 3)
          echo "PROXY_ADDRESS=$PROXY_ADDRESS" >> $GITHUB_ENV
          echo "Proxy contract deployed at address $PROXY_ADDRESS"
        env:
          MNEMONIC: ${{ secrets.MNEMONIC }}

        

